//Series & Studies
export const ADD_STUDY = 'ADD_STUDY'
export const ADD_SERIES = 'ADD_SERIES'
export const ADD_INSTANCE = 'ADD_INSTANCE'
export const ADD_WARNING_SERIES = 'ADD_WARNING_SERIES'
export const UPDATE_WARNING_SERIES = 'UPDATE_WARNING_SERIES'
export const UPDATE_WARNING_STUDY = 'UPDATE_WARNING_STUDY'

//Tables
export const SELECT_STUDY = 'SELECT_STUDY'
export const SELECT_SERIES = 'SELECT_SERIES'